[init]
name = "tedgectl"
is_available = ["@CONFIG_DIR@/bin/tedgectl", "is_available"]
restart = ["@CONFIG_DIR@/bin/tedgectl", "restart", "{}"]
stop =  ["@CONFIG_DIR@/bin/tedgectl", "stop", "{}"]
enable =  ["@CONFIG_DIR@/bin/tedgectl", "enable", "{}"]
disable =  ["@CONFIG_DIR@/bin/tedgectl", "disable", "{}"]
is_active = ["@CONFIG_DIR@/bin/tedgectl", "is_active", "{}"]

[system]
reboot = ["sh", "-c", "sync; sync; sleep 2; reboot"]
