[config]
version = "2"

[c8y.proxy.client]
host = "127.0.0.1"

[mqtt.client]
host = "127.0.0.1"

[mqtt.bridge]
built_in = true

[logs]
path = "/var/log/tedge"

[tmp]
path = "/tmp"

[data]
path = "/tmp/tedge"
