name: build

on:
  push:
    tags:
      - "*"
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build ${{ matrix.target.arch }}
    runs-on: ubuntu-latest
    strategy:
        fail-fast: false
        matrix:
          target:
            - arch: aarch64-linux-musl
            - arch: arm-linux-musleabihf
            - arch: arm-linux-musleabi
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: taiki-e/install-action@just
      - name: Build
        run: just build ${{ matrix.target.arch }}

      - name: Upload packages as zip
        # https://github.com/marketplace/actions/upload-a-build-artifact
        uses: actions/upload-artifact@v4
        with:
            name: tedge-standalone-${{ matrix.target.arch }}
            path: tedge-standalone-${{ matrix.target.arch }}.tar.gz

  release:
    runs-on: ubuntu-latest
    needs: [build]
    if: |
      always() &&
      startsWith(github.ref, 'refs/tags/') &&
      needs.build.result == 'success'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Download release artifacts
        uses: actions/download-artifact@v4
        with:
          path: tmp/
      - name: Release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          generate_release_notes: false
          draft: true
          files: |
            tmp/**/*.tar.gz
